tsuji:
  rag:
    index-path: tsuji-index
  translator:
    language:
      source: en
      destination: ja
quarkus:
  package:
    jar:
      type: "uber-jar"
      add-runner-suffix: false
  langchain4j:
    ai:
      gemini:
        log-requests: true
        log-responses: true
        timeout: 60s
  config:
    locations:
      - "application.local.yml"
